In [24]:
import pandas as pd
data = pd.read_csv(r'C:\Users\Bhargav Patel\Desktop\Machine learning_jupyter_notebook\Machine_Learning_Data_Preprocessing_Python-master\MallCustomers.csv')
data.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [25]:
y = data.iloc[:,:-1].values
x = data.iloc[:,0:4].values
x

array([[1, 'Male', 19, 15],
       [2, 'Male', 21, 15],
       [3, 'Female', 20, 16],
       [4, 'Female', 23, 16],
       [5, 'Female', 31, 17],
       [6, 'Female', 22, 17],
       [7, 'Female', 35, 18],
       [8, 'Female', 23, 18],
       [9, 'Male', 64, 19],
       [10, 'Female', 30, 19],
       [11, 'Male', 67, 19],
       [12, 'Female', 35, 19],
       [13, 'Female', 58, 20],
       [14, 'Female', 24, 20],
       [15, 'Male', 37, 20],
       [16, 'Male', 22, 20],
       [17, 'Female', 35, 21],
       [18, 'Male', 20, 21],
       [19, 'Male', 52, 23],
       [20, 'Female', 35, 23],
       [21, 'Male', 35, 24],
       [22, 'Male', 25, 24],
       [23, 'Female', 46, 25],
       [24, 'Male', 31, 25],
       [25, 'Female', 54, 28],
       [26, 'Male', 29, 28],
       [27, 'Female', 45, 28],
       [28, 'Male', 35, 28],
       [29, 'Female', 40, 29],
       [30, 'Female', 23, 29],
       [31, 'Male', 60, 30],
       [32, 'Female', 21, 30],
       [33, 'Male', 53, 33],
       [34, 'Mal

In [33]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
x[:,1] = LE.fit_transform(x[:,1])
x

array([[1, 1, 19, 15],
       [2, 1, 21, 15],
       [3, 0, 20, 16],
       [4, 0, 23, 16],
       [5, 0, 31, 17],
       [6, 0, 22, 17],
       [7, 0, 35, 18],
       [8, 0, 23, 18],
       [9, 1, 64, 19],
       [10, 0, 30, 19],
       [11, 1, 67, 19],
       [12, 0, 35, 19],
       [13, 0, 58, 20],
       [14, 0, 24, 20],
       [15, 1, 37, 20],
       [16, 1, 22, 20],
       [17, 0, 35, 21],
       [18, 1, 20, 21],
       [19, 1, 52, 23],
       [20, 0, 35, 23],
       [21, 1, 35, 24],
       [22, 1, 25, 24],
       [23, 0, 46, 25],
       [24, 1, 31, 25],
       [25, 0, 54, 28],
       [26, 1, 29, 28],
       [27, 0, 45, 28],
       [28, 1, 35, 28],
       [29, 0, 40, 29],
       [30, 0, 23, 29],
       [31, 1, 60, 30],
       [32, 0, 21, 30],
       [33, 1, 53, 33],
       [34, 1, 18, 33],
       [35, 0, 49, 33],
       [36, 0, 21, 33],
       [37, 0, 42, 34],
       [38, 0, 30, 34],
       [39, 0, 36, 37],
       [40, 0, 20, 37],
       [41, 0, 65, 38],
       [42, 1, 24, 38],
 

In [34]:
# In LableEncoding there is a one problem   ...  here it set male -- > 1   and female -- > 0  ..,and then it gives high priority to male...
# To avoid this we use OneHotEncoder  --->>  it creates different collumns according to categories...like  male, female..
#after doing LableEncoding we have to do OneHotEncoding to avoid priorites...

from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(categorical_features = [1])   # it set for index no. 1 ...  categorical feeature means index...
x = OHE.fit_transform(x).toarray()
x

C:\Users\Bhargav Patel\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Bhargav Patel\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[  0.,   1.,   1.,  19.,  15.],
       [  0.,   1.,   2.,  21.,  15.],
       [  1.,   0.,   3.,  20.,  16.],
       [  1.,   0.,   4.,  23.,  16.],
       [  1.,   0.,   5.,  31.,  17.],
       [  1.,   0.,   6.,  22.,  17.],
       [  1.,   0.,   7.,  35.,  18.],
       [  1.,   0.,   8.,  23.,  18.],
       [  0.,   1.,   9.,  64.,  19.],
       [  1.,   0.,  10.,  30.,  19.],
       [  0.,   1.,  11.,  67.,  19.],
       [  1.,   0.,  12.,  35.,  19.],
       [  1.,   0.,  13.,  58.,  20.],
       [  1.,   0.,  14.,  24.,  20.],
       [  0.,   1.,  15.,  37.,  20.],
       [  0.,   1.,  16.,  22.,  20.],
       [  1.,   0.,  17.,  35.,  21.],
       [  0.,   1.,  18.,  20.,  21.],
       [  0.,   1.,  19.,  52.,  23.],
       [  1.,   0.,  20.,  35.,  23.],
       [  0.,   1.,  21.,  35.,  24.],
       [  0.,   1.,  22.,  25.,  24.],
       [  1.,   0.,  23.,  46.,  25.],
       [  0.,   1.,  24.,  31.,  25.],
       [  1.,   0.,  25.,  54.,  28.],
       [  0.,   1.,  26.,